require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SkModulesController do

  def mock_sk_module(stubs={})
    @mock_sk_module ||= mock_model(SkModule, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all sk_modules as @sk_modules" do
      SkModule.stub(:all) { [mock_sk_module] }
      get :index
      assigns(:sk_modules).should eq([mock_sk_module])
    end
  end

  describe "GET show" do
    it "assigns the requested sk_module as @sk_module" do
      SkModule.stub(:find).with("37") { mock_sk_module }
      get :show, :id => "37"
      assigns(:sk_module).should be(mock_sk_module)
    end
  end

  describe "GET new" do
    it "assigns a new sk_module as @sk_module" do
      SkModule.stub(:new) { mock_sk_module }
      get :new
      assigns(:sk_module).should be(mock_sk_module)
    end
  end

  describe "GET edit" do
    it "assigns the requested sk_module as @sk_module" do
      SkModule.stub(:find).with("37") { mock_sk_module }
      get :edit, :id => "37"
      assigns(:sk_module).should be(mock_sk_module)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created sk_module as @sk_module" do
        SkModule.stub(:new).with({'these' => 'params'}) { mock_sk_module(:save => true) }
        post :create, :sk_module => {'these' => 'params'}
        assigns(:sk_module).should be(mock_sk_module)
      end

      it "redirects to the created sk_module" do
        SkModule.stub(:new) { mock_sk_module(:save => true) }
        post :create, :sk_module => {}
        response.should redirect_to(sk_module_url(mock_sk_module))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sk_module as @sk_module" do
        SkModule.stub(:new).with({'these' => 'params'}) { mock_sk_module(:save => false) }
        post :create, :sk_module => {'these' => 'params'}
        assigns(:sk_module).should be(mock_sk_module)
      end

      it "re-renders the 'new' template" do
        SkModule.stub(:new) { mock_sk_module(:save => false) }
        post :create, :sk_module => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sk_module" do
        SkModule.stub(:find).with("37") { mock_sk_module }
        mock_sk_module.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :sk_module => {'these' => 'params'}
      end

      it "assigns the requested sk_module as @sk_module" do
        SkModule.stub(:find) { mock_sk_module(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:sk_module).should be(mock_sk_module)
      end

      it "redirects to the sk_module" do
        SkModule.stub(:find) { mock_sk_module(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(sk_module_url(mock_sk_module))
      end
    end

    describe "with invalid params" do
      it "assigns the sk_module as @sk_module" do
        SkModule.stub(:find) { mock_sk_module(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:sk_module).should be(mock_sk_module)
      end

      it "re-renders the 'edit' template" do
        SkModule.stub(:find) { mock_sk_module(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sk_module" do
      SkModule.stub(:find).with("37") { mock_sk_module }
      mock_sk_module.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the sk_modules list" do
      SkModule.stub(:find) { mock_sk_module }
      delete :destroy, :id => "1"
      response.should redirect_to(sk_modules_url)
    end
  end

end
